export const SET_MDB_PATH = "SET_MDB_PATH";

export const CHANGE_CAMPAIGN_VIEW_STATE = "CHANGE_CAMPAIGN_VIEW_STATE";

export const INIT_CAMPAIGN_DATA = "INIT_CAMPAIGN_DATA";

export const SET_SELECTED_CAMPAIGN_INDEX = "SET_SELECTED_CAMPAIGN_INDEX";