export const SET_MDB_DATA = "SET_MDB_DATA";

export const INIT_CAMPAIGN_DATA = "INIT_CAMPAIGN_DATA";

export const INIT_TEMP_GROUP_DATA = "INIT_TEMP_GROUP_DATA";

export const INIT_GROUP_DATA = "INIT_GROUP_DATA";

export const INIT_UPLOAD_DATA = "INIT_UPLOAD_DATA";